# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f0ced8188e9b3fc6c2646adb26436b1fcd1ee3525032f877adea9ace8fd814905f22a2006c0ee775f342357115c5a8ce38bee2b28a274073a6b92a3388e732a

test:
  secret_key_base: 497e7e92cdb935da2480fd990791c8cd20e158c48dc12ce476248ef990fe2225c489023623daf69598cab406529aee05707b0031827ac970a56d7d031e00ccd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
